# utils/mapeamentos.py

# Mapeia palavras-chave encontradas nos nomes de DEPARTAMENTOS do Senior 
# para os valores `similarTo` equivalentes da Gupy.
MAPA_DEPARTAMENTOS = {
    "tecnologia": "technology",
    "sistemas": "technology",
    "infraestrutura": "technology",
    "segurança": "security",
    "vendas": "sales",
    "ven": "sales",
    "exportação": "sales",
    "loja": "sales",
    "televendas": "sales",
    "suprimentos": "purchases",
    "supply": "purchases",
    "processos": "project_or_processes",
    "produção": "operations",
    "producao": "operations",
    "pinos": "operations",
    "implantes" : "operations",
    "banco de talentos": "operations",
    "embalagem": "operations",
    "envase": "operations",
    "cavibrush": "operations",
    "almoxarifado": "logistics",
    "logistica": "logistics",
    "ppcpm": "logistics",
    "exportacao": "logistics",
    "laboratorio": "innovation_or_product",
    "produtos": "innovation_or_product",
    "lixas": "innovation_or_product",
    "relacionamento": "innovation_or_product",
    "consultoria": "innovation_or_product",
    "orientacao": "innovation_or_product",
    "pesquisa e desenvolvimento": "innovation_or_product",
    "gestao pessoas": "human_resources",
    "governanca": "human_resources",
    "humanos": "human_resources",
    "financeiro": "financial_management",
    "administração": "financial_management",
    "diretoria": "financial_management",
    "manutencao": "engineering_or_maintenance_or_technical_services",
    "engenharia": "engineering_or_maintenance_or_technical_services",
    "marketing": "communication_or_design_or_marketing",
    "criação": "communication_or_design_or_marketing",
    "criacao": "communication_or_design_or_marketing",
    "qualidade": "audit_or_quality",
    "seguranca": "audit_or_quality",
    "controladoria" : "audit_or_quality",
    "projetos" : "audit_or_quality",
    "materiais":  "audit_or_quality",
    "central de relacionamento": "attendance",
    "contas": "accounting_or_controlling",
    "contabilidade": "accounting_or_controlling",
    "contábil": "accounting_or_controlling",
}

# Mapeia palavras-chave encontradas nos nomes de CARGOS do Senior 
# para os valores `similarTo` equivalentes da Gupy.
MAPA_CARGOS = {
    "analista": "analyst",
    "atendente": "analyst",
    "designer": "analyst",
    "preparador": "analyst",
    "programador": "analyst",
    "assistente": "auxiliary",
    "recepcionista": "auxiliary",
    "auxiliar": "auxiliary",
    "consultor": "consultant",
    "coordenador": "coordinator",
    "estagiario": "intern",
    "inspetor": "technician",
    "metrologista": "technician",
    "técnico": "technician",
    "supervisor": "supervisor",
    "líder": "supervisor",
    "cientifico": "specialist",
    "especialista": "specialist",
    "pesquisador": "specialist",
    "operador": "operator",
    "almoxarife": "operator",
    "torneiro": "operator",
    "gerente": "manager",
}